name: flutter_resp
description: "Easy to use responsive framework for flutter"
version: 1.0.0
repository: https://github.com/thadathilsinan/flutter_resp
issue_tracker: https://github.com/thadathilsinan/flutter_resp/issues
documentation: https://github.com/thadathilsinan/flutter_resp
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
topics:
  - responsive
  - tailwind
  - css
  - web

environment:
  sdk: ">=3.2.6 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
